package com.github.papahigh

import org.knowm.xchange.currency.Currency.BTC
import org.knowm.xchange.currency.CurrencyPair


fun main() {

    var exchange = Exchange.bitfinex()
    var arbitrage = Arbitrage(Config.sources)

    val market = Market.Builder.of(Config.currencyPairs)
        .withTickers(exchange.getTickers(Config.currencyPairs))
        .withListener(arbitrage)
        .build()

    for (pair in Config.currencyPairs) {
        exchange.subscribe(pair) { market.update(it) }
    }
}

object Config {

    var sources = listOf(BTC)

    val currencyPairs = listOf(
        "ADA/BTC",
        "ADA/USD",
        "ADA/UST",
        "ALG/USD",
        "AMP/USD",
        "AMP/UST",
        "APE/USD",
        "APE/UST",
        "APT/USD",
        "APT/UST",
        "ARB/USD",
        "ARB/UST",
        "ATH/USD",
        "ATH/UST",
        "ATO/USD",
        "ATO/UST",
        "B2M/USD",
        "B2M/UST",
        "BGB/USD",
        "BGB/UST",
        "BTC/EUR",
        "BTC/GBP",
        "BTC/JPY",
        "BTC/TRY",
        "BTC/USD",
        "BTC/UST",
        "BTT/USD",
        "BXN/USD",
        "BXN/UST",
        "CCD/USD",
        "CCD/UST",
        "CHZ/USD",
        "CHZ/UST",
        "CRV/USD",
        "CRV/UST",
        "DAI/USD",
        "DOP/USD",
        "DOP/UST",
        "DOT/USD",
        "DOT/UST",
        "DSH/BTC",
        "DSH/USD",
        "DYM/USD",
        "DYM/UST",
        "ENA/USD",
        "ENA/UST",
        "EOS/BTC",
        "EOS/USD",
        "EOS/UST",
        "ETC/BTC",
        "ETC/USD",
        "ETC/UST",
        "ETH/BTC",
        "ETH/EUR",
        "ETH/GBP",
        "ETH/JPY",
        "ETH/USD",
        "ETH/UST",
        "EUR/UST",
        "EUT/USD",
        "EUT/UST",
        "FET/USD",
        "FET/UST",
        "FIL/USD",
        "FIL/UST",
        "FTM/USD",
        "FTM/UST",
        "GBP/UST",
        "GRT/USD",
        "GRT/UST",
        "GTX/USD",
        "GTX/UST",
        "HIX/USD",
        "HIX/UST",
        "ICP/USD",
        "ICP/UST",
        "IOT/BTC",
        "IOT/USD",
        "JPY/UST",
        "JST/USD",
        "JST/UST",
        "JUP/USD",
        "JUP/UST",
        "JXX/USD",
        "JXX/UST",
        "KAN/USD",
        "KAN/UST",
        "LDO/USD",
        "LDO/UST",
        "LEO/BTC",
        "LEO/ETH",
        "LEO/USD",
        "LEO/UST",
        "LTC/BTC",
        "LTC/USD",
        "LTC/UST",
        "MEW/USD",
        "MEW/UST",
        "MIM/USD",
        "MIM/UST",
        "MKR/USD",
        "MKR/UST",
        "MLN/USD",
        "MNA/USD",
        "MPC/USD",
        "MPC/UST",
        "NEO/USD",
        "NEO/UST",
        "NOT/USD",
        "NOT/UST",
        "NYM/USD",
        "NYM/UST",
        "OMG/BTC",
        "OMG/USD",
        "OMN/USD",
        "OPX/USD",
        "OPX/UST",
        "PNK/USD",
        "POL/USD",
        "POL/UST",
        "RRT/USD",
        "SEI/USD",
        "SEI/UST",
        "SOL/BTC",
        "SOL/USD",
        "SOL/UST",
        "STG/USD",
        "STG/UST",
        "SUI/USD",
        "SUI/UST",
        "SUN/USD",
        "SUN/UST",
        "TIA/USD",
        "TIA/UST",
        "TON/USD",
        "TON/UST",
        "TRX/BTC",
        "TRX/EUR",
        "TRX/USD",
        "TRX/UST",
        "TRY/UST",
        "TSD/USD",
        "TSD/UST",
        "UDC/USD",
        "UDC/UST",
        "UNI/USD",
        "UNI/UST",
        "UOS/BTC",
        "UOS/USD",
        "UST/USD",
        "WBT/BTC",
        "WBT/USD",
        "WIF/USD",
        "WIF/UST",
        "WOO/USD",
        "WOO/UST",
        "XDC/USD",
        "XDC/UST",
        "XLM/BTC",
        "XLM/USD",
        "XLM/UST",
        "XMR/BTC",
        "XMR/USD",
        "XMR/UST",
        "XRD/BTC",
        "XRD/USD",
        "XRP/BTC",
        "XRP/USD",
        "XRP/UST",
        "XTP/USD",
        "XTP/UST",
        "XTZ/USD",
        "YFI/USD",
        "YFI/UST",
        "ZEC/BTC",
        "ZEC/USD",
        "ZKX/USD",
        "ZKX/UST",
        "ZRO/USD",
        "ZRO/UST",
        "ZRX/USD"
    )
        .subList(0, 30) // Subscription Limit on public market data https://docs.bitfinex.com/docs/ws-general
        .map { CurrencyPair(it) }
}
